apiVersion: v1
kind: Service
metadata:
  name: mydockerapppc-sevice
spec:
  selector:
    app: mydockerapppc
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  ports:
  - port: 3306
  selector:
    app: mysqlinstance
  clusterIP: None